# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - name: git-checkout
#        uses: actions/checkout@v3
#        with:
#          ref: master
#
#      - name: Install
#        run: npm install
#
#      - name: Build
#        run: npm run build
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          scp_source: ./github-cd/*
          scp_target: /usr/share/nginx/html
          before_script: |
            df -h
          after_script: |
            whoami
