# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm install
      - name: Build
        run: npm run build

      - name: deploy file to server
        uses: ilCollez/ssh-scp-deploy@main
        with:
          host: '175.99.21.37'
          port: 22
          username: 'root'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          files: './github-cd/*'
          remote-path: '/usr/share/nginx/html'
          clean: true
